/**
 * Type definitions for the simulation engine
 */

import type { Order, Policy, EvaluationResult } from '@guardrail-sim/policy-engine';

// ============================================================================
// PERSONA TYPES
// ============================================================================

/**
 * Strategy type for buyer personas
 */
export type PersonaStrategy = 'cooperative' | 'strategic' | 'adversarial';

/**
 * A buyer persona that generates discount requests
 */
export interface BuyerPersona {
  id: string;
  name: string;
  strategy: PersonaStrategy;
  /** Range of discount values this persona will request (0-1) */
  discountRange: { min: number; max: number };
  /** Range of order quantities this persona will use */
  volumeRange: { min: number; max: number };
  /** Range of product margins for generated orders */
  marginRange: { min: number; max: number };
  /** Maximum negotiation rounds before abandoning */
  maxRounds: number;
  /** How much to adjust strategy after rejection (0-1) */
  adaptationRate: number;
}

/**
 * Interface for generating discount requests.
 * Deterministic personas implement this directly.
 * Future LLM-backed personas can implement this behind an API call.
 */
export interface PersonaProvider {
  generateRequest(context: NegotiationContext): DiscountRequest;
}

/**
 * Context available to a persona when generating a request
 */
export interface NegotiationContext {
  persona: BuyerPersona;
  roundNumber: number;
  previousResult: EvaluationResult | null;
  previousDiscount: number | null;
  order: Order;
}

/**
 * A discount request generated by a persona
 */
export interface DiscountRequest {
  proposedDiscount: number;
  order: Order;
}

// ============================================================================
// SESSION TYPES
// ============================================================================

/**
 * Outcome of a negotiation session
 */
export type SessionOutcome = 'accepted' | 'rejected' | 'abandoned';

/**
 * A single round in a negotiation session
 */
export interface NegotiationRound {
  roundNumber: number;
  proposedDiscount: number;
  order: Order;
  evaluation: EvaluationResult;
  accepted: boolean;
}

/**
 * A complete negotiation session between a persona and the policy engine
 */
export interface NegotiationSession {
  id: string;
  persona: BuyerPersona;
  rounds: NegotiationRound[];
  outcome: SessionOutcome;
  finalDiscount: number | null;
  marginImpact: number;
}

// ============================================================================
// SIMULATION CONFIGURATION
// ============================================================================

/**
 * Configuration for running a simulation
 */
export interface SimulationConfig {
  policy: Policy;
  personas: BuyerPersona[];
  /** Number of negotiation sessions per persona */
  ordersPerPersona: number;
  /** Seed for reproducible random number generation */
  seed?: number;
}

// ============================================================================
// RESULTS AND METRICS
// ============================================================================

/**
 * An edge case discovered during simulation
 */
export interface EdgeCase {
  description: string;
  session: NegotiationSession;
  severity: 'info' | 'warning' | 'critical';
}

/**
 * Aggregated metrics from a simulation run
 */
export interface SimulationMetrics {
  totalSessions: number;
  approvalRate: number;
  averageDiscountApproved: number;
  averageDiscountRequested: number;
  averageMarginAfterDiscount: number;
  violationsByRule: Record<string, number>;
  outcomesByPersona: Record<string, { accepted: number; rejected: number; abandoned: number }>;
  limitingFactors: Record<string, number>;
  edgeCasesFound: EdgeCase[];
}

/**
 * Complete results from a simulation run
 */
export interface SimulationResults {
  config: SimulationConfig;
  sessions: NegotiationSession[];
  metrics: SimulationMetrics;
  timestamp: Date;
}
